# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/.dependabot/git-actions" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/.dependabot/npm/json" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    
  - package-ecosystem: "docker"
    directory: "/.dependabot/docker/dockfile"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100

