name: Feature Request
description: File a feature request with Issue Forms(BETA)
title: "[Enhacement]: <title>"
labels: ["enhancement"]
assignees:
  - bossOfCode
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request form!
  - type: textarea
    id: how-improve
    attributes:
      label: How do you want us to improve?
      description: Give us details of how you want us to improve.
      placeholder: How can we improve?
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other
      description: Any other suggestions?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kamehameha-studios/kamehameha-studios.github.io/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
